name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'ga'
    - name: Setup NASM
      uses: ilammy/setup-nasm@main
    - name: Perform the Debug Build
      run: dotnet build -c Debug
    - name: Test
      run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: ./Linq2d.Tests/TestResults/coverage.info ./Linq2d.Tests.Vectorization/TestResults/coverage.info ./ImageHelpers.Tests/TestResults/coverage.info
        format: lcov
      continue-on-error: true
    - name: Perform the Release Build
      run: dotnet build -c Release
    - name: Benchmark
      run: cd Linq2d.Benchmarks; sudo dotnet run -c Release --no-build --filter "*";
    - name: Check benchmark results
      run: ls ./Linq2d.Benchmarks/BenchmarkDotNet.Artifacts/results/*.csv
    - name: Update benchmark results 
      uses: EndBug/add-and-commit@main
      with:
        message: 'Updating the benchmark results'
        add: './Linq2d.Benchmarks/BenchmarkDotNet.Artifacts/results/*.csv'
