name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'ga'
    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
    - name: Test
      run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: ./Linq2d.Tests/TestResults/coverage.info ./Linq2d.Tests.Vectorization/TestResults/coverage.info
      continue-on-error: true
    - name: Perform the Release Build
      run: dotnet build -c Release
    - name: Benchmark
      run: cd Linq2d.Benchmarks; sudo dotnet run -c Release --no-build --filter "*";
